swagger: '2.0'
info:
  title: FespCdService
  description: ''
  x-ibm-name: fespcdservice
  version: 1.0.0
schemes:
  - https
basePath: /FespCdService
produces:
  - application/xml
consumes:
  - text/xml
securityDefinitions:
  clientID:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    description: ''
security:
  - clientID: []
x-ibm-configuration:
  type: wsdl
  phase: realized
  enforced: true
  testable: true
  gateway: datapower-gateway
  cors:
    enabled: true
  wsdl-definition:
    wsdl: /home/lskoder/workspace/italia-pagopa-api/wsdl/nodo/CdPerNodo.wsdl
    service: FespCdService
    port: FespCdPortType
    soap-version: '1.1'
  assembly:
    execute:
      - proxy:
          title: proxy
          target-url: 'http://PuntoAccessoCD.spcoop.gov.it/'
paths:
  /cdInfoPagamento:
    post:
      summary: Operation cdInfoPagamento
      description: ''
      operationId: cdInfoPagamento
      x-ibm-soap:
        soap-action: cdInfoPagamento
        soap-operation: '{http://ws.pagamenti.telematici.gov/}cdInfoPagamento'
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/cdInfoPagamentoInput'
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/cdInfoPagamentoOutput'
definitions:
  Security:
    xml:
      namespace: >-
        http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd
      prefix: wsse
    type: object
    properties:
      UsernameToken:
        xml:
          namespace: >-
            http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd
          prefix: wsse
        type: object
        properties:
          Username:
            xml:
              namespace: >-
                http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd
              prefix: wsse
            type: string
          Password:
            xml:
              namespace: >-
                http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd
              prefix: wsse
            type: string
          Nonce:
            xml:
              namespace: >-
                http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd
              prefix: wsse
            type: string
            properties:
              EncodingType:
                xml:
                  namespace: ''
                  attribute: true
                type: string
          Created:
            xml:
              namespace: >-
                http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd
              prefix: wsu
            type: string
      Timestamp:
        xml:
          namespace: >-
            http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd
          prefix: wsu
        type: object
        properties:
          Created:
            xml:
              namespace: >-
                http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd
              prefix: wsu
            type: string
          Expires:
            xml:
              namespace: >-
                http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd
              prefix: wsu
            type: string
          Id:
            xml:
              namespace: >-
                http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd
              prefix: wsu
              attribute: true
            type: string
  cdInfoPagamentoInput:
    type: object
    properties:
      Envelope:
        xml:
          prefix: soapenv
          namespace: 'http://schemas.xmlsoap.org/soap/envelope/'
        type: object
        properties:
          Header:
            $ref: '#/definitions/cdInfoPagamentoHeader'
          Body:
            type: object
            properties:
              cdInfoPagamento:
                $ref: '#/definitions/cdInfoPagamento_ppt'
            required:
              - cdInfoPagamento
        required:
          - Body
    required:
      - Envelope
    example: >-

      <soapenv:Envelope
      xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
       <soapenv:Header>
        <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
         <wsse:UsernameToken>
          <wsse:Username>string</wsse:Username>
          <wsse:Password>string</wsse:Password>
          <wsse:Nonce EncodingType="string">string</wsse:Nonce>
          <wsu:Created>string</wsu:Created>
         </wsse:UsernameToken>
         <wsu:Timestamp wsu:Id="string">
          <wsu:Created>string</wsu:Created>
          <wsu:Expires>string</wsu:Expires>
         </wsu:Timestamp>
        </wsse:Security>
       </soapenv:Header>
       <soapenv:Body>
        <ppt:cdInfoPagamento xmlns:ppt="http://ws.pagamenti.telematici.gov/"><!-- mandatory -->
         <identificativoDominio><!-- mandatory -->string</identificativoDominio>
         <identificativoUnivocoVersamento><!-- mandatory -->string</identificativoUnivocoVersamento>
         <codiceContestoPagamento><!-- mandatory -->string</codiceContestoPagamento>
         <idPagamento><!-- mandatory -->string</idPagamento>
        </ppt:cdInfoPagamento>
       </soapenv:Body>
      </soapenv:Envelope>
  cdInfoPagamentoHeader:
    type: object
    properties:
      Security:
        $ref: '#/definitions/Security'
  cdInfoPagamentoOutput:
    type: object
    properties:
      Envelope:
        xml:
          prefix: soapenv
          namespace: 'http://schemas.xmlsoap.org/soap/envelope/'
        type: object
        properties:
          Body:
            type: object
            properties:
              cdInfoPagamentoResponse:
                $ref: '#/definitions/cdInfoPagamentoResponse_ppt'
        required:
          - Body
    required:
      - Envelope
    example: >-

      <soapenv:Envelope
      xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
       <soapenv:Body>
        <ppt:cdInfoPagamentoResponse xmlns:ppt="http://ws.pagamenti.telematici.gov/">
         <fault>
          <faultCode><!-- mandatory -->string</faultCode>
          <faultString><!-- mandatory -->string</faultString>
          <id><!-- mandatory -->string</id>
          <description>string</description>
          <serial>3</serial>
          <originalFaultCode>string</originalFaultCode>
          <originalFaultString>string</originalFaultString>
          <originalDescription>string</originalDescription>
         </fault>
         <esito>string</esito>
        </ppt:cdInfoPagamentoResponse>
       </soapenv:Body>
      </soapenv:Envelope>
  cdInfoPagamento_ppt:
    xml:
      namespace: 'http://ws.pagamenti.telematici.gov/'
      prefix: ppt
    type: object
    properties:
      identificativoDominio:
        $ref: '#/definitions/stText35_ppt'
      identificativoUnivocoVersamento:
        $ref: '#/definitions/stText35_ppt'
      codiceContestoPagamento:
        $ref: '#/definitions/stText35_ppt'
      idPagamento:
        type: string
        xml:
          namespace: ''
    required:
      - identificativoDominio
      - identificativoUnivocoVersamento
      - codiceContestoPagamento
      - idPagamento
    example: |-

      <ppt:cdInfoPagamento xmlns:ppt="http://ws.pagamenti.telematici.gov/">
       <identificativoDominio><!-- mandatory -->string</identificativoDominio>
       <identificativoUnivocoVersamento><!-- mandatory -->string</identificativoUnivocoVersamento>
       <codiceContestoPagamento><!-- mandatory -->string</codiceContestoPagamento>
       <idPagamento><!-- mandatory -->string</idPagamento>
      </ppt:cdInfoPagamento>
  cdInfoPagamentoResponse_ppt:
    xml:
      namespace: 'http://ws.pagamenti.telematici.gov/'
      prefix: ppt
    allOf:
      - $ref: '#/definitions/risposta_ppt'
      - xml:
          namespace: 'http://ws.pagamenti.telematici.gov/'
          prefix: ppt
        type: object
        properties:
          esito:
            type: string
            xml:
              namespace: ''
    example: >-

      <ppt:cdInfoPagamentoResponse
      xmlns:ppt="http://ws.pagamenti.telematici.gov/">
       <fault>
        <faultCode><!-- mandatory -->string</faultCode>
        <faultString><!-- mandatory -->string</faultString>
        <id><!-- mandatory -->string</id>
        <description>string</description>
        <serial>3</serial>
        <originalFaultCode>string</originalFaultCode>
        <originalFaultString>string</originalFaultString>
        <originalDescription>string</originalDescription>
       </fault>
       <esito>string</esito>
      </ppt:cdInfoPagamentoResponse>
  stText35_ppt:
    xml:
      namespace: ''
    type: string
    maxLength: 35
    minLength: 1
    x-xsi-type: stText35
    x-xsi-type-xml:
      namespace: 'http://ws.pagamenti.telematici.gov/'
      prefix: ppt
    x-xsi-type-uniquename: stText35_ppt
  risposta_ppt:
    xml:
      namespace: ''
      prefix: ''
    type: object
    properties:
      fault:
        $ref: '#/definitions/ctFaultBean_ppt'
    x-xsi-type: risposta
    x-xsi-type-xml:
      namespace: 'http://ws.pagamenti.telematici.gov/'
      prefix: ppt
    x-xsi-type-uniquename: risposta_ppt
    x-ibm-discriminator: true
  ctFaultBean_ppt:
    xml:
      namespace: ''
      prefix: ''
    type: object
    properties:
      faultCode:
        type: string
      faultString:
        type: string
      id:
        type: string
      description:
        type: string
      serial:
        type: integer
        format: int32
      originalFaultCode:
        type: string
      originalFaultString:
        type: string
      originalDescription:
        type: string
    required:
      - faultCode
      - faultString
      - id
    x-xsi-type: ctFaultBean
    x-xsi-type-xml:
      namespace: 'http://ws.pagamenti.telematici.gov/'
      prefix: ppt
    x-xsi-type-uniquename: ctFaultBean_ppt
